### ISSUE TITLE
Responsive design is broken on mobile devices.

### ISSUE THREAD

**Issue by ashleyadams12** [ashleyadams12/Responsive-Blog-Template#1]
The navigation bar does not collapse properly on smaller screens.

**Comment by ashleyadams12** [comment]
Hi! I noticed this issue. Would you like me to work on fixing it?

**Comment by ashleyadams12** [comment]
Hello Aryan, I'd like if you help me solve this issue.

**Comment by aryangupttaa** [comment]
Can you zip the project to me?

**Comment by aryangupttaa** [comment]
Here's my email id - aryangupta159119@gmail.com

**Comment by ashleyadams12** [comment]
ok i have sent you the zip code

**Comment by aryangupttaa** [comment]
Hey it seems that you had problem in in your "mobile.css" file. I have edited the file and uploaded it as "mobile1.css" you can download it and check, it's working good now even on small devices.

**Comment by ashleyadams12** [comment]
Thank you Aryan the blog web app is now working good.
